% -------------------------------------------------------------------
%  Generated by MATLAB on 22-Mar-2026 17:55:49
%  MATLAB version: 24.2.0.2923080 (R2024b) Update 6
% -------------------------------------------------------------------
                                      

PAR_TIRE_agv_InitSpeed = Simulink.Parameter;
PAR_TIRE_agv_InitSpeed.Value = slexpr("((PAR_BODY_v_InitVelocity/3.6)/PAR_TIRE_d_RollingRadius)");
PAR_TIRE_agv_InitSpeed.Complexity = 'real';
PAR_TIRE_agv_InitSpeed.CoderInfo.StorageClass = 'Auto';
PAR_TIRE_agv_InitSpeed.Description = '';
PAR_TIRE_agv_InitSpeed.DataType = 'auto';
PAR_TIRE_agv_InitSpeed.Min = [];
PAR_TIRE_agv_InitSpeed.Max = [];
PAR_TIRE_agv_InitSpeed.DocUnits = '';

PAR_TIRE_d_RollingRadius = Simulink.Parameter;
PAR_TIRE_d_RollingRadius.Value = 0.275;
PAR_TIRE_d_RollingRadius.Complexity = 'real';
PAR_TIRE_d_RollingRadius.CoderInfo.StorageClass = 'Auto';
PAR_TIRE_d_RollingRadius.Description = '';
PAR_TIRE_d_RollingRadius.DataType = 'auto';
PAR_TIRE_d_RollingRadius.Min = [];
PAR_TIRE_d_RollingRadius.Max = [];
PAR_TIRE_d_RollingRadius.DocUnits = '';

PAR_TIRE_f_PeakLongForce = Simulink.Parameter;
PAR_TIRE_f_PeakLongForce.Value = slexpr("(PAR_TIRE_f_RatedVerLoad*0.9)");
PAR_TIRE_f_PeakLongForce.Complexity = 'real';
PAR_TIRE_f_PeakLongForce.CoderInfo.StorageClass = 'Auto';
PAR_TIRE_f_PeakLongForce.Description = '';
PAR_TIRE_f_PeakLongForce.DataType = 'auto';
PAR_TIRE_f_PeakLongForce.Min = [];
PAR_TIRE_f_PeakLongForce.Max = [];
PAR_TIRE_f_PeakLongForce.DocUnits = '';

PAR_TIRE_f_RatedVerLoad = Simulink.Parameter;
PAR_TIRE_f_RatedVerLoad.Value = slexpr("(PAR_BODY_m_Mass/4)*9.81");
PAR_TIRE_f_RatedVerLoad.Complexity = 'real';
PAR_TIRE_f_RatedVerLoad.CoderInfo.StorageClass = 'Auto';
PAR_TIRE_f_RatedVerLoad.Description = '';
PAR_TIRE_f_RatedVerLoad.DataType = 'auto';
PAR_TIRE_f_RatedVerLoad.Min = [];
PAR_TIRE_f_RatedVerLoad.Max = [];
PAR_TIRE_f_RatedVerLoad.DocUnits = '';

PAR_TIRE_j_Inertia = Simulink.Parameter;
PAR_TIRE_j_Inertia.Value = slexpr("25*(PAR_TIRE_d_RollingRadius^2)");
PAR_TIRE_j_Inertia.Complexity = 'real';
PAR_TIRE_j_Inertia.CoderInfo.StorageClass = 'Auto';
PAR_TIRE_j_Inertia.Description = '';
PAR_TIRE_j_Inertia.DataType = 'auto';
PAR_TIRE_j_Inertia.Min = [];
PAR_TIRE_j_Inertia.Max = [];
PAR_TIRE_j_Inertia.DocUnits = '';

PAR_TIRE_nr_SlipAtPeakForce = Simulink.Parameter;
PAR_TIRE_nr_SlipAtPeakForce.Value = 0.15;
PAR_TIRE_nr_SlipAtPeakForce.Complexity = 'real';
PAR_TIRE_nr_SlipAtPeakForce.CoderInfo.StorageClass = 'Auto';
PAR_TIRE_nr_SlipAtPeakForce.Description = '';
PAR_TIRE_nr_SlipAtPeakForce.DataType = 'auto';
PAR_TIRE_nr_SlipAtPeakForce.Min = [];
PAR_TIRE_nr_SlipAtPeakForce.Max = [];
PAR_TIRE_nr_SlipAtPeakForce.DocUnits = '';

