% -------------------------------------------------------------------
%  Generated by MATLAB on 24-Mar-2026 18:43:28
%  MATLAB version: 24.2.0.2923080 (R2024b) Update 6
% -------------------------------------------------------------------
                                              

PAR_BODY_a_FrontalArea = Simulink.Parameter;
PAR_BODY_a_FrontalArea.Value = 3;
PAR_BODY_a_FrontalArea.Complexity = 'real';
PAR_BODY_a_FrontalArea.CoderInfo.StorageClass = 'Auto';
PAR_BODY_a_FrontalArea.Description = '';
PAR_BODY_a_FrontalArea.DataType = 'auto';
PAR_BODY_a_FrontalArea.Min = [];
PAR_BODY_a_FrontalArea.Max = [];
PAR_BODY_a_FrontalArea.DocUnits = '';

PAR_BODY_d_FrontToCG = Simulink.Parameter;
PAR_BODY_d_FrontToCG.Value = 1.4;
PAR_BODY_d_FrontToCG.Complexity = 'real';
PAR_BODY_d_FrontToCG.CoderInfo.StorageClass = 'Auto';
PAR_BODY_d_FrontToCG.Description = '';
PAR_BODY_d_FrontToCG.DataType = 'auto';
PAR_BODY_d_FrontToCG.Min = [];
PAR_BODY_d_FrontToCG.Max = [];
PAR_BODY_d_FrontToCG.DocUnits = '';

PAR_BODY_d_HeightCG = Simulink.Parameter;
PAR_BODY_d_HeightCG.Value = 0.5;
PAR_BODY_d_HeightCG.Complexity = 'real';
PAR_BODY_d_HeightCG.CoderInfo.StorageClass = 'Auto';
PAR_BODY_d_HeightCG.Description = '';
PAR_BODY_d_HeightCG.DataType = 'auto';
PAR_BODY_d_HeightCG.Min = [];
PAR_BODY_d_HeightCG.Max = [];
PAR_BODY_d_HeightCG.DocUnits = '';

PAR_BODY_d_RearToCG = Simulink.Parameter;
PAR_BODY_d_RearToCG.Value = 1.6;
PAR_BODY_d_RearToCG.Complexity = 'real';
PAR_BODY_d_RearToCG.CoderInfo.StorageClass = 'Auto';
PAR_BODY_d_RearToCG.Description = '';
PAR_BODY_d_RearToCG.DataType = 'auto';
PAR_BODY_d_RearToCG.Min = [];
PAR_BODY_d_RearToCG.Max = [];
PAR_BODY_d_RearToCG.DocUnits = '';

PAR_BODY_m_Mass = Simulink.Parameter;
PAR_BODY_m_Mass.Value = 1200;
PAR_BODY_m_Mass.Complexity = 'real';
PAR_BODY_m_Mass.CoderInfo.StorageClass = 'Auto';
PAR_BODY_m_Mass.Description = '';
PAR_BODY_m_Mass.DataType = 'auto';
PAR_BODY_m_Mass.Min = [];
PAR_BODY_m_Mass.Max = [];
PAR_BODY_m_Mass.DocUnits = 'kg';

PAR_BODY_nr_DragCoeff = Simulink.Parameter;
PAR_BODY_nr_DragCoeff.Value = 0.4;
PAR_BODY_nr_DragCoeff.Complexity = 'real';
PAR_BODY_nr_DragCoeff.CoderInfo.StorageClass = 'Auto';
PAR_BODY_nr_DragCoeff.Description = '';
PAR_BODY_nr_DragCoeff.DataType = 'auto';
PAR_BODY_nr_DragCoeff.Min = [];
PAR_BODY_nr_DragCoeff.Max = [];
PAR_BODY_nr_DragCoeff.DocUnits = '';

PAR_BODY_nr_Wheels = Simulink.Parameter;
PAR_BODY_nr_Wheels.Value = 2;
PAR_BODY_nr_Wheels.Complexity = 'real';
PAR_BODY_nr_Wheels.CoderInfo.StorageClass = 'Auto';
PAR_BODY_nr_Wheels.Description = '';
PAR_BODY_nr_Wheels.DataType = 'auto';
PAR_BODY_nr_Wheels.Min = [];
PAR_BODY_nr_Wheels.Max = [];
PAR_BODY_nr_Wheels.DocUnits = '';

PAR_BODY_rho_AirDensity = Simulink.Parameter;
PAR_BODY_rho_AirDensity.Value = 1.18;
PAR_BODY_rho_AirDensity.Complexity = 'real';
PAR_BODY_rho_AirDensity.CoderInfo.StorageClass = 'Auto';
PAR_BODY_rho_AirDensity.Description = '';
PAR_BODY_rho_AirDensity.DataType = 'auto';
PAR_BODY_rho_AirDensity.Min = [];
PAR_BODY_rho_AirDensity.Max = [];
PAR_BODY_rho_AirDensity.DocUnits = '';

PAR_BODY_v_InitVelocity = Simulink.Parameter;
PAR_BODY_v_InitVelocity.Value = 130;
PAR_BODY_v_InitVelocity.Complexity = 'real';
PAR_BODY_v_InitVelocity.CoderInfo.StorageClass = 'Auto';
PAR_BODY_v_InitVelocity.Description = '';
PAR_BODY_v_InitVelocity.DataType = 'auto';
PAR_BODY_v_InitVelocity.Min = [];
PAR_BODY_v_InitVelocity.Max = [];
PAR_BODY_v_InitVelocity.DocUnits = 'kph';

